openapi: 3.0.0
info:
  title: "RP Flask REST API"
  description: "An API about people and notes"
  version: "1.0.0"

servers:
  - url: "/api"

paths:
  /image/get-props:
    get:
      operationId: "image.get_image_base_props"
      tags:
        - "Image"
      summary: "Processamento da imagem"
      responses:
        "200":
          description: "Successfully read image.py data"